import { useState } from 'react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';
import { captureProductEvent } from '../../lib/product-analytics';

/**
 * Market Intelligence is gated behind authentication only (any signed-in user
 * can join the waitlist). The earlier Pro+ tier gate was tied to the fake
 * AI-comps generator, which has been removed pending real MLS comp data.
 */

const ROADMAP_REPORTS = [
  { icon: '🏘️', title: 'Comparable Listings (Comps)',     desc: 'Real MLS comps — price range, DOM, and key differentiators for the Charleston metro.' },
  { icon: '📊', title: 'Neighborhood Price Trends',       desc: 'Median sold price, DOM, and price-per-sqft trends for Charleston-area neighborhoods.' },
  { icon: '📈', title: 'Market Velocity Report',          desc: 'Absorption rates and list-to-close ratios by neighborhood and price tier.' },
  { icon: '🌊', title: 'Coastal Premium Analysis',        desc: "Quantify the Shem Creek, Sullivan's Island, and Isle of Palms proximity premium." },
  { icon: '📅', title: 'Seasonal Listing Intelligence',   desc: 'Best times to list by neighborhood, property type, and price band.' },
  { icon: '👥', title: 'Team Performance Dashboard',      desc: 'Generations, copy rates, and listing performance across your entire team.' },
];

type WaitlistStatus =
  | { state: 'idle' }
  | { state: 'submitting' }
  | { state: 'success' }
  | { state: 'error'; message: string };

export default function ReportsPage() {
  const { user } = useAuth();
  const [email, setEmail] = useState(user?.email ?? '');
  const [status, setStatus] = useState<WaitlistStatus>({ state: 'idle' });

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = email.trim().toLowerCase();
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed)) {
      setStatus({ state: 'error', message: 'Please enter a valid email address.' });
      return;
    }
    setStatus({ state: 'submitting' });
    const { error } = await supabase
      .from('early_access_waitlist')
      .insert({ email: trimmed, source: 'reports' });
    if (error) {
      const duplicate = error.code === '23505' || /duplicate|unique/i.test(error.message);
      if (duplicate) {
        setStatus({ state: 'success' });
        captureProductEvent('early_access_waitlist_joined', { source: 'reports', duplicate: true });
        return;
      }
      setStatus({ state: 'error', message: error.message || 'Could not join the waitlist. Please try again.' });
      return;
    }
    captureProductEvent('early_access_waitlist_joined', { source: 'reports', duplicate: false });
    setStatus({ state: 'success' });
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 920, margin: '0 auto' }}>
      <div
        className="glass-featured"
        style={{ padding: '38px 36px' }}
      >
        <div className="tag tag-magenta">Coming Q3 2026</div>

        <h1
          style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            fontWeight: 800,
            fontSize: 'clamp(28px, 4vw, 40px)',
            color: 'var(--text-hi)',
            lineHeight: 1.1,
            letterSpacing: '-0.02em',
            margin: '14px 0 14px',
          }}
        >
          Market Intelligence
          <br />
          <span className="shimmer-text">for the Charleston metro.</span>
        </h1>

        <p
          style={{
            fontFamily: 'DM Sans, system-ui, sans-serif',
            fontSize: 16,
            lineHeight: 1.75,
            color: 'var(--text-mid)',
            margin: '0 0 28px',
            maxWidth: 620,
          }}
        >
          Real MLS comps coming Q3 2026. We're partnering with Charleston-area MLS feeds
          so the comps you see are pulled from actual sold and active listings — not
          generated by a language model. Join the early access list to be first in line.
        </p>

        <form
          onSubmit={submit}
          style={{
            display: 'flex',
            gap: 10,
            flexWrap: 'wrap',
            maxWidth: 520,
            marginBottom: 12,
          }}
        >
          <label htmlFor="waitlist-email" className="neon-label" style={{ width: '100%' }}>
            EARLY ACCESS EMAIL
          </label>
          <input
            id="waitlist-email"
            type="email"
            autoComplete="email"
            placeholder="you@charlestonbrokerage.com"
            value={email}
            onChange={(e) => {
              setEmail(e.target.value);
              if (status.state === 'error') setStatus({ state: 'idle' });
            }}
            disabled={status.state === 'submitting' || status.state === 'success'}
            className="neon-input"
            style={{ flex: '1 1 260px', minWidth: 0 }}
            required
          />
          <button
            type="submit"
            className="btn btn-primary"
            disabled={status.state === 'submitting' || status.state === 'success'}
          >
            {status.state === 'submitting'
              ? 'Joining…'
              : status.state === 'success'
                ? '✓ On the list'
                : 'Join early access →'}
          </button>
        </form>

        {status.state === 'success' && (
          <p
            style={{
              fontFamily: "'DM Mono', ui-monospace, monospace",
              fontSize: 10,
              color: 'var(--cyan)',
              letterSpacing: '.12em',
              margin: '12px 0 0',
            }}
          >
            YOU'RE ON THE LIST. WE'LL EMAIL WHEN COMPS GO LIVE.
          </p>
        )}

        {status.state === 'error' && (
          <p
            style={{
              fontFamily: "'DM Mono', ui-monospace, monospace",
              fontSize: 10,
              color: 'var(--magenta)',
              letterSpacing: '.12em',
              margin: '12px 0 0',
            }}
            role="alert"
          >
            {status.message.toUpperCase()}
          </p>
        )}

        <p
          style={{
            fontFamily: "'DM Mono', ui-monospace, monospace",
            fontSize: 9,
            color: 'var(--text-ghost)',
            letterSpacing: '.14em',
            margin: '18px 0 0',
          }}
        >
          NO MARKETING SPAM · WE EMAIL ONCE WHEN COMPS LAUNCH
        </p>
      </div>

      <div
        style={{
          padding: '20px 22px',
          background: 'rgba(10,10,32,0.5)',
          border: '1px dashed var(--cyan-border)',
          borderRadius: 14,
        }}
      >
        <div
          style={{
            fontFamily: "'DM Mono', ui-monospace, monospace",
            fontSize: 9,
            color: 'var(--text-lo)',
            letterSpacing: '.14em',
            marginBottom: 4,
          }}
        >
          ON THE ROADMAP
        </div>
        <div
          style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            fontWeight: 700,
            fontSize: 15,
            color: 'var(--text-hi)',
            marginBottom: 18,
          }}
        >
          What's shipping with Market Intelligence
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
            gap: 10,
          }}
        >
          {ROADMAP_REPORTS.map((r) => (
            <div
              key={r.title}
              style={{
                padding: '14px 16px',
                background: 'rgba(0,0,0,0.2)',
                border: '1px solid rgba(255,255,255,0.06)',
                borderRadius: 10,
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                <span style={{ fontSize: 16 }}>{r.icon}</span>
                <span
                  style={{
                    fontFamily: "'Playfair Display', Georgia, serif",
                    fontWeight: 600,
                    fontSize: 12.5,
                    color: 'var(--text-mid)',
                  }}
                >
                  {r.title}
                </span>
              </div>
              <p
                style={{
                  fontFamily: 'DM Sans, sans-serif',
                  fontSize: 11.5,
                  color: 'var(--text-lo)',
                  lineHeight: 1.55,
                  margin: 0,
                }}
              >
                {r.desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
